trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
  paths:
    include:
    - '*'
    - src/libraries/System.Private.CoreLib/*
    exclude:
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

variables:
  - template: /eng/pipelines/common/variables.yml

schedules:
- cron: "30 2 * * *"
  displayName: Every night at 2:30AM
  branches:
    include:
    - main
  always: true

jobs:

- ${{ if and(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.DefinitionName'], 'perf-wasm')) }}:
  - template: /eng/pipelines/coreclr/perf-wasm-jobs.yml

- ${{ if not(and(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.DefinitionName'], 'perf-wasm'))) }}:
  - template: /eng/pipelines/coreclr/perf-non-wasm-jobs.yml
